USE [master]
GO

/****** Object:  Database [LDW_Archive]    Script Date: 06/23/2015 09:47:50 ******/
CREATE DATABASE [LDW_Archive] ON  PRIMARY 
( NAME = N'LDW_Archive_01', FILENAME = N'C:\FT\db27\MSSQL\DATA\LDW_Archive\LDW_Archive_01.mdf' , SIZE = 10240KB , MAXSIZE = UNLIMITED, FILEGROWTH = 10%), 
 FILEGROUP [DATA_FG]  DEFAULT 
( NAME = N'LDW_Archive_DATA_FG_01', FILENAME = N'C:\FT\db31\MSSQL\DATA\LDW_Archive\LDW_Archive_DATA_FG_01.mdf' , SIZE = 102400000KB , MAXSIZE = UNLIMITED, FILEGROWTH = 10%), 
( NAME = N'LDW_Archive_DATA_FG_02', FILENAME = N'C:\FT\db32\MSSQL\DATA\LDW_Archive\LDW_Archive_DATA_FG_02.ndf' , SIZE = 103283520KB , MAXSIZE = UNLIMITED, FILEGROWTH = 10%), 
( NAME = N'LDW_Archive_DATA_FG_03', FILENAME = N'C:\FT\db33\MSSQL\DATA\LDW_Archive\LDW_Archive_DATA_FG_03.ndf' , SIZE = 103283520KB , MAXSIZE = UNLIMITED, FILEGROWTH = 10%), 
( NAME = N'LDW_Archive_DATA_FG_04', FILENAME = N'C:\FT\db29\MSSQL\DATA\LDW_Archive\LDW_Archive_DATA_FG_04.ndf' , SIZE = 103283520KB , MAXSIZE = UNLIMITED, FILEGROWTH = 10%), 
( NAME = N'LDW_Archive_DATA_FG_05', FILENAME = N'C:\FT\db28\MSSQL\DATA\LDW_Archive\LDW_Archive_DATA_FG_05.ndf' , SIZE = 103283520KB , MAXSIZE = UNLIMITED, FILEGROWTH = 10%), 
( NAME = N'LDW_Archive_DATA_FG_06', FILENAME = N'C:\FT\db34\MSSQL\DATA\LDW_Archive\LDW_Archive_DATA_FG_06.ndf' , SIZE = 103283520KB , MAXSIZE = UNLIMITED, FILEGROWTH = 10%), 
( NAME = N'LDW_Archive_DATA_FG_07', FILENAME = N'C:\FT\db35\MSSQL\DATA\LDW_Archive\LDW_Archive_DATA_FG_07.ndf' , SIZE = 113611904KB , MAXSIZE = UNLIMITED, FILEGROWTH = 10%), 
( NAME = N'LDW_Archive_DATA_FG_08', FILENAME = N'C:\FT\db36\MSSQL\DATA\LDW_Archive\LDW_Archive_DATA_FG_08.ndf' , SIZE = 113611904KB , MAXSIZE = UNLIMITED, FILEGROWTH = 10%), 
( NAME = N'LDW_Archive_DATA_FG_09', FILENAME = N'C:\FT\db30\MSSQL\DATA\LDW_Archive\LDW_Archive_DATA_FG_09.ndf' , SIZE = 104448000KB , MAXSIZE = UNLIMITED, FILEGROWTH = 10%), 
( NAME = N'LDW_Archive_DATA_FG_10', FILENAME = N'C:\FT\db38\MSSQL\DATA\LDW_Archive\LDW_Archive_DATA_FG_10.ndf' , SIZE = 98304000KB , MAXSIZE = UNLIMITED, FILEGROWTH = 10%)
 LOG ON 
( NAME = N'LDW_Archive_log_01', FILENAME = N'C:\FT\Log04\MSSQL\Log\LDW_Archive\LDW_Archive_log_01.ldf' , SIZE = 101748032KB , MAXSIZE = 2048GB , FILEGROWTH = 10%), 
( NAME = N'LDW_Archive_log_02', FILENAME = N'C:\FT\Log04\MSSQL\Log\LDW_Archive\LDW_Archive_log_02.ldf' , SIZE = 92498176KB , MAXSIZE = 2048GB , FILEGROWTH = 10%), 
( NAME = N'LDW_Archive_log_03', FILENAME = N'C:\FT\Log04\MSSQL\Log\LDW_Archive\LDW_Archive_log_03.ldf' , SIZE = 92498176KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [LDW_Archive] SET COMPATIBILITY_LEVEL = 100
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [LDW_Archive].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [LDW_Archive] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [LDW_Archive] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [LDW_Archive] SET ANSI_PADDING ON 
GO

ALTER DATABASE [LDW_Archive] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [LDW_Archive] SET ARITHABORT OFF 
GO

ALTER DATABASE [LDW_Archive] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [LDW_Archive] SET AUTO_CREATE_STATISTICS ON 
GO

ALTER DATABASE [LDW_Archive] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [LDW_Archive] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [LDW_Archive] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [LDW_Archive] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [LDW_Archive] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [LDW_Archive] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [LDW_Archive] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [LDW_Archive] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [LDW_Archive] SET  DISABLE_BROKER 
GO

ALTER DATABASE [LDW_Archive] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [LDW_Archive] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [LDW_Archive] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [LDW_Archive] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [LDW_Archive] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [LDW_Archive] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [LDW_Archive] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [LDW_Archive] SET  READ_WRITE 
GO

ALTER DATABASE [LDW_Archive] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [LDW_Archive] SET  MULTI_USER 
GO

ALTER DATABASE [LDW_Archive] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [LDW_Archive] SET DB_CHAINING OFF 
GO


